### ISSUE TITLE
UFLoss

### ISSUE THREAD

**Issue by PASSENGER128** [mikgroup/UFLoss#1]
i'm wondering that if your UFLoss model can use in other dataset,also knee dataset. my dataset is MICCAI13_SegChallenge.

**Comment by KeWang0622** [comment]
Sure! Our UFLoss model can be definitely used in other datasets, but I think you may have to retrain the model. What you have to do is just simply crop patches from the training sets and use them to train the UFLoss model. FYI, I haven't demonstrated our UFLoss in Segmentation tasks. You might also have to change the code a little bit if your data is magnitude instead of complex data.
